version: '3.8'

services:
  strapi:
    image: strapi/strapi
    container_name: ${PROJECT_NAME:-strapi}_strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_NAME: ${DATABASE_NAME:-strapidb}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapidb_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-P@ssw0rd}
      DATABASE_SSL: ${DATABASE_SSL:-false}
    volumes:
      - ./packages/backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    cap_add:
      - SYS_NICE

  mysql:
    image: mysql
    container_name: ${PROJECT_NAME:-mysql}_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./packages/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-r00tP@ssw0rd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-strapidb}
      MYSQL_USER: ${MYSQL_USER:-strapidb_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-P@ssw0rd}